<div class="static-page">
<h1>Depositing data or metadata with the Microdata Library</h1>
<div class="info-box">
<?php 
$message = (isset($projects[0]->id)) ? t('intro_projects_exist') : t('intro_no_projects');
$link = '<a href="' . site_url('datadeposit/projects') .'">' . $message  . '</a>';
echo $link
?>
</div>
<p><em>Do you have data or metadata related to a study not currently available in the Development Data Platform (DPP) Microdata Library?</em></p>
<p><em>Would you like to deposit these data or metadata with the Microdata Library for display or dissemination through the DDP Microdata Catalog?</em></p>
<p>We are currently developing a data deposit application which will be available from this link to make this easy for you to do. In the mean time though you are welcome to contact us [ email address] with requests to deposit data and we will assist you in making this happen.</p>
<p>What type of information and materials are required to facilitate easy preparation of your data for the Catalog?</p>
<ul>
<li>Some background information on the Study e.g. short abstract, principal investigators, funders</li>
<li>The data - preferably in one of the major statistical package formats with all of the variables labeled and value labels applied.</li>
<li>All the survey instruments used e.g. Questionnaires, Tests, and Diaries etc.</li>
<li>Information on survey methodology e.g. sampling, weighting</li>
<li>Other material that may be helpful to users e.g. maps, code lists, program files for cleaning or deriving variables.</li>
<li>Any reports, presentations or other useful information generated by the study.</li>
<li>Some indication of who the owners of the data are i.e. the World Bank or some other institution.</li>
</ul>
<p>Note: if you do not have the microdata files, but have all the other relevant metadata then deposting the metadata only is acceptable.</p>
</div>
