<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

/**
 * Core display composite renderers registry
 *
 * Template nodes reference a renderer via display_options.renderer (preferred)
 * or legacy display_options.field_template (view basename, resolved at runtime).
 *
 * Scalar fields use built-in renderers (format, linkify, layout) — not listed here.
 * Entries with kind "widget" are layout blocks (DOI citation, iframe embed), not metadata fields.
 * Custom widgets: application/config/display_renderers_custom.php plus a PHP view.
 *
 * supported_data_types (optional): restrict to catalog project types (script, survey, …).
 * Omit or leave empty to allow every data type. Aliases match display templates
 * (survey/microdata, timeseries/indicator, timeseries-db/timeseriesdb).
 *
 * params[] schema (UI-only; PHP views read saved display_options keys):
 *   type         Control type (currently text)
 *   label        Inspector field label
 *   description  Optional caption under the control (omit if the label is enough)
 */
$config['display_renderers'] = array(
	'field_array' => array(
		'key' => 'field_array',
		'kind' => 'composite',
		'label' => 'Table',
		'field_template' => 'field_array',
		'supported_source_types' => array('array', 'nested_array'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_array'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_authors' => array(
		'key' => 'field_authors',
		'kind' => 'composite',
		'label' => 'Authors table',
		'field_template' => 'field_authors',
		'supported_source_types' => array('array', 'nested_array'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_authors'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_array_tags' => array(
		'key' => 'field_array_tags',
		'kind' => 'composite',
		'label' => 'Keyword tags',
		'field_template' => 'field_array_tags',
		'supported_source_types' => array('array'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_array_tags'),
		'default_params' => array('tag_column' => 'name'),
		'params' => array(
			'tag_column' => array(
				'type' => 'text',
				'label' => 'Tag column key',
				'description' => 'Which array column to show as the tag text. Default is name.',
			),
		),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_array_list' => array(
		'key' => 'field_array_list',
		'kind' => 'composite',
		'label' => 'Array list',
		'field_template' => 'field_array_list',
		'supported_source_types' => array('array'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_array_list'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_array_accordion' => array(
		'key' => 'field_array_accordion',
		'kind' => 'composite',
		'label' => 'Accordion',
		'field_template' => 'field_array_accordion',
		'supported_source_types' => array('nested_array'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_array_accordion'),
		'default_params' => array(),
		'params' => array(
			'header_fields' => array(
				'type' => 'text',
				'label' => 'Record heading fields',
				'description' => 'Comma-separated column keys for each card title. First non-empty wins.',
			),
		),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_array_stacked' => array(
		'key' => 'field_array_stacked',
		'kind' => 'composite',
		'label' => 'Stacked records',
		'field_template' => 'field_array_stacked',
		'supported_source_types' => array('nested_array'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_array_stacked'),
		'default_params' => array(),
		'params' => array(
			'header_fields' => array(
				'type' => 'text',
				'label' => 'Record heading fields',
				'description' => 'Comma-separated column keys for each record heading. First non-empty wins.',
			),
		),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_bounding_box' => array(
		'key' => 'field_bounding_box',
		'kind' => 'composite',
		'label' => 'Bounding box',
		'field_template' => 'field_bounding_box',
		'supported_source_types' => array('array'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_bounding_box'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_geospatial_bbox' => array(
		'key' => 'field_geospatial_bbox',
		'kind' => 'composite',
		'label' => 'Geospatial bounding box',
		'field_template' => 'field_geospatial_bbox',
		'supported_source_types' => array('nested_array'),
		'supported_data_types' => array('geospatial'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_geospatial_bbox'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_geog_contact' => array(
		'key' => 'field_geog_contact',
		'kind' => 'composite',
		'label' => 'Geospatial contact',
		'field_template' => 'field_geog_contact',
		'supported_source_types' => array('array', 'nested_array'),
		'supported_data_types' => array('geospatial'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_geog_contact'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_geo_lineage' => array(
		'key' => 'field_geo_lineage',
		'kind' => 'composite',
		'label' => 'Geospatial lineage',
		'field_template' => 'field_geo_lineage',
		'supported_source_types' => array('array', 'nested_array'),
		'supported_data_types' => array('geospatial'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_geo_lineage'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_feature_catalog' => array(
		'key' => 'field_feature_catalog',
		'kind' => 'composite',
		'label' => 'Feature catalogue',
		'field_template' => 'field_feature_catalog',
		'supported_source_types' => array('object'),
		'supported_data_types' => array('geospatial'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_feature_catalog'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_photo_gallery' => array(
		'key' => 'field_photo_gallery',
		'kind' => 'composite',
		'label' => 'Photo gallery',
		'field_template' => 'field_photo_gallery',
		'supported_source_types' => array('array'),
		'supported_data_types' => array('geospatial', 'image'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_photo_gallery'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_resources' => array(
		'key' => 'field_resources',
		'kind' => 'composite',
		'label' => 'Online resources',
		'field_template' => 'field_resources',
		'supported_source_types' => array('array'),
		'supported_data_types' => array('geospatial'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_resources'),
		'default_params' => array('exclude' => 'pic'),
		'params' => array(
			'exclude' => array(
				'type' => 'text',
				'label' => 'Exclude dctype codes',
				'description' => 'dctype code to hide (legacy default is pic so images stay in the gallery).',
			),
		),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_array_badge' => array(
		'key' => 'field_array_badge',
		'kind' => 'composite',
		'label' => 'Badge chips',
		'field_template' => 'field_array_badge',
		'supported_source_types' => array('array', 'simple_array'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_array_badge'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_ts_databases' => array(
		'key' => 'field_ts_databases',
		'kind' => 'composite',
		'label' => 'Timeseries databases',
		'field_template' => 'field_ts_databases',
		'supported_source_types' => array('array'),
		'supported_data_types' => array('timeseries'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_ts_databases'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_scripts_script' => array(
		'key' => 'field_scripts_script',
		'kind' => 'composite',
		'label' => 'Script resources',
		'field_template' => 'field_scripts_script',
		'supported_source_types' => array('array', 'nested_array'),
		'supported_data_types' => array('script'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_scripts_script'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_text_inline' => array(
		'key' => 'field_text_inline',
		'kind' => 'composite',
		'label' => 'Inline text (legacy)',
		'field_template' => 'field_text_inline',
		'supported_source_types' => array('string', 'text', 'number', 'integer', 'boolean', 'date'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_text_inline'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => false,
		'status' => 'inactive',
	),
	'field_object_additional' => array(
		'key' => 'field_object_additional',
		'kind' => 'composite',
		'label' => 'Open object',
		'field_template' => 'field_object_additional',
		'supported_source_types' => array('object', 'array', 'nested_array'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_object_additional'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_video' => array(
		'key' => 'field_video',
		'kind' => 'composite',
		'label' => 'Video embed',
		'field_template' => 'field_video',
		'supported_source_types' => array('string', 'text', 'object'),
		'supported_data_types' => array('video'),
		'handler' => array('type' => 'php_composite', 'id' => 'field_video'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_doi_citation' => array(
		'key' => 'field_doi_citation',
		'kind' => 'widget',
		'label' => 'DOI citation',
		'field_template' => 'field_doi-citation',
		'supported_source_types' => array('widget'),
		'data_source' => 'doi',
		'handler' => array('type' => 'php_widget', 'id' => 'field_doi-citation'),
		'default_params' => array(),
		'params' => array(
			'data_key' => array(
				'type' => 'text',
				'label' => 'Identifiers field key',
				'description' => 'Optional. Default is this catalog type’s identifiers array, then the study DOI and DataCite DOI.',
			),
		),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
	'field_iframe_embed' => array(
		'key' => 'field_iframe_embed',
		'kind' => 'widget',
		'label' => 'Iframe embed',
		'field_template' => 'field_widget_default',
		'supported_source_types' => array('widget'),
		'data_source' => 'iframe_embeds',
		'handler' => array('type' => 'php_widget', 'id' => 'field_widget_default'),
		'default_params' => array(),
		'params' => array(),
		'supports_layout_builder' => true,
		'status' => 'active',
	),
);
