<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| ISO 639-1 Language List
|--------------------------------------------------------------------------
|
*/

$config['iso_languages'] = [
    'af'    => ['name' => 'Afrikaans',              'display' => 'Afrikaans',           'direction' => 'ltr'],
    'sq'    => ['name' => 'Albanian',               'display' => 'Shqip',               'direction' => 'ltr'],
    'am'    => ['name' => 'Amharic',                'display' => 'አማርኛ',                'direction' => 'ltr'],
    'ar'    => ['name' => 'Arabic',                 'display' => 'العربية',              'direction' => 'rtl'],
    'hy'    => ['name' => 'Armenian',               'display' => 'Հայերեն',             'direction' => 'ltr'],
    'az'    => ['name' => 'Azerbaijani',            'display' => 'Azərbaycanca',         'direction' => 'ltr'],
    'eu'    => ['name' => 'Basque',                 'display' => 'Euskara',              'direction' => 'ltr'],
    'be'    => ['name' => 'Belarusian',             'display' => 'Беларуская',           'direction' => 'ltr'],
    'bn'    => ['name' => 'Bengali',                'display' => 'বাংলা',               'direction' => 'ltr'],
    'bs'    => ['name' => 'Bosnian',                'display' => 'Bosanski',             'direction' => 'ltr'],
    'bg'    => ['name' => 'Bulgarian',              'display' => 'Български',            'direction' => 'ltr'],
    'ca'    => ['name' => 'Catalan',                'display' => 'Català',               'direction' => 'ltr'],
    'zh'    => ['name' => 'Chinese (Simplified)',   'display' => '中文（简体）',           'direction' => 'ltr'],
    'zh-TW' => ['name' => 'Chinese (Traditional)', 'display' => '中文（繁體）',           'direction' => 'ltr'],
    'hr'    => ['name' => 'Croatian',               'display' => 'Hrvatski',             'direction' => 'ltr'],
    'cs'    => ['name' => 'Czech',                  'display' => 'Čeština',              'direction' => 'ltr'],
    'da'    => ['name' => 'Danish',                 'display' => 'Dansk',                'direction' => 'ltr'],
    'nl'    => ['name' => 'Dutch',                  'display' => 'Nederlands',           'direction' => 'ltr'],
    'en'    => ['name' => 'English',                'display' => 'English',              'direction' => 'ltr'],
    'et'    => ['name' => 'Estonian',               'display' => 'Eesti',                'direction' => 'ltr'],
    'fi'    => ['name' => 'Finnish',                'display' => 'Suomi',                'direction' => 'ltr'],
    'fr'    => ['name' => 'French',                 'display' => 'Français',             'direction' => 'ltr'],
    'gl'    => ['name' => 'Galician',               'display' => 'Galego',               'direction' => 'ltr'],
    'ka'    => ['name' => 'Georgian',               'display' => 'ქართული',              'direction' => 'ltr'],
    'de'    => ['name' => 'German',                 'display' => 'Deutsch',              'direction' => 'ltr'],
    'el'    => ['name' => 'Greek',                  'display' => 'Ελληνικά',             'direction' => 'ltr'],
    'gu'    => ['name' => 'Gujarati',               'display' => 'ગુજરાતી',              'direction' => 'ltr'],
    'ht'    => ['name' => 'Haitian Creole',         'display' => 'Kreyòl Ayisyen',       'direction' => 'ltr'],
    'ha'    => ['name' => 'Hausa',                  'display' => 'Hausa',                'direction' => 'ltr'],
    'he'    => ['name' => 'Hebrew',                 'display' => 'עברית',               'direction' => 'rtl'],
    'hi'    => ['name' => 'Hindi',                  'display' => 'हिन्दी',              'direction' => 'ltr'],
    'hu'    => ['name' => 'Hungarian',              'display' => 'Magyar',               'direction' => 'ltr'],
    'is'    => ['name' => 'Icelandic',              'display' => 'Íslenska',             'direction' => 'ltr'],
    'ig'    => ['name' => 'Igbo',                   'display' => 'Igbo',                 'direction' => 'ltr'],
    'id'    => ['name' => 'Indonesian',             'display' => 'Bahasa Indonesia',     'direction' => 'ltr'],
    'ga'    => ['name' => 'Irish',                  'display' => 'Gaeilge',              'direction' => 'ltr'],
    'it'    => ['name' => 'Italian',                'display' => 'Italiano',             'direction' => 'ltr'],
    'ja'    => ['name' => 'Japanese',               'display' => '日本語',               'direction' => 'ltr'],
    'kn'    => ['name' => 'Kannada',                'display' => 'ಕನ್ನಡ',               'direction' => 'ltr'],
    'kk'    => ['name' => 'Kazakh',                 'display' => 'Қазақша',              'direction' => 'ltr'],
    'km'    => ['name' => 'Khmer',                  'display' => 'ភាសាខ្មែរ',            'direction' => 'ltr'],
    'rw'    => ['name' => 'Kinyarwanda',            'display' => 'Kinyarwanda',          'direction' => 'ltr'],
    'ko'    => ['name' => 'Korean',                 'display' => '한국어',               'direction' => 'ltr'],
    'ku'    => ['name' => 'Kurdish',                'display' => 'کوردی',               'direction' => 'rtl'],
    'ky'    => ['name' => 'Kyrgyz',                 'display' => 'Кыргызча',             'direction' => 'ltr'],
    'lo'    => ['name' => 'Lao',                    'display' => 'ລາວ',                  'direction' => 'ltr'],
    'lv'    => ['name' => 'Latvian',                'display' => 'Latviešu',             'direction' => 'ltr'],
    'lt'    => ['name' => 'Lithuanian',             'display' => 'Lietuvių',             'direction' => 'ltr'],
    'lb'    => ['name' => 'Luxembourgish',          'display' => 'Lëtzebuergesch',       'direction' => 'ltr'],
    'mk'    => ['name' => 'Macedonian',             'display' => 'Македонски',           'direction' => 'ltr'],
    'mg'    => ['name' => 'Malagasy',               'display' => 'Malagasy',             'direction' => 'ltr'],
    'ms'    => ['name' => 'Malay',                  'display' => 'Bahasa Melayu',        'direction' => 'ltr'],
    'ml'    => ['name' => 'Malayalam',              'display' => 'മലയാളം',              'direction' => 'ltr'],
    'mt'    => ['name' => 'Maltese',                'display' => 'Malti',                'direction' => 'ltr'],
    'mi'    => ['name' => 'Maori',                  'display' => 'Māori',                'direction' => 'ltr'],
    'mr'    => ['name' => 'Marathi',                'display' => 'मराठी',               'direction' => 'ltr'],
    'mn'    => ['name' => 'Mongolian',              'display' => 'Монгол',               'direction' => 'ltr'],
    'my'    => ['name' => 'Myanmar (Burmese)',      'display' => 'မြန်မာဘာသာ',           'direction' => 'ltr'],
    'ne'    => ['name' => 'Nepali',                 'display' => 'नेपाली',              'direction' => 'ltr'],
    'no'    => ['name' => 'Norwegian',              'display' => 'Norsk',                'direction' => 'ltr'],
    'ny'    => ['name' => 'Nyanja (Chichewa)',      'display' => 'Chichewa',             'direction' => 'ltr'],
    'or'    => ['name' => 'Odia (Oriya)',           'display' => 'ଓଡ଼ିଆ',               'direction' => 'ltr'],
    'ps'    => ['name' => 'Pashto',                 'display' => 'پښتو',                'direction' => 'rtl'],
    'fa'    => ['name' => 'Persian',                'display' => 'فارسی',               'direction' => 'rtl'],
    'pl'    => ['name' => 'Polish',                 'display' => 'Polski',               'direction' => 'ltr'],
    'pt'    => ['name' => 'Portuguese',             'display' => 'Português',            'direction' => 'ltr'],
    'pa'    => ['name' => 'Punjabi',                'display' => 'ਪੰਜਾਬੀ',              'direction' => 'ltr'],
    'ro'    => ['name' => 'Romanian',               'display' => 'Română',               'direction' => 'ltr'],
    'ru'    => ['name' => 'Russian',                'display' => 'Русский',              'direction' => 'ltr'],
    'sm'    => ['name' => 'Samoan',                 'display' => 'Gagana Samoa',         'direction' => 'ltr'],
    'gd'    => ['name' => 'Scots Gaelic',           'display' => 'Gàidhlig',             'direction' => 'ltr'],
    'sr'    => ['name' => 'Serbian',                'display' => 'Српски',               'direction' => 'ltr'],
    'st'    => ['name' => 'Sesotho',                'display' => 'Sesotho',              'direction' => 'ltr'],
    'sn'    => ['name' => 'Shona',                  'display' => 'Shona',                'direction' => 'ltr'],
    'sd'    => ['name' => 'Sindhi',                 'display' => 'سنڌي',                'direction' => 'rtl'],
    'si'    => ['name' => 'Sinhala',                'display' => 'සිංහල',               'direction' => 'ltr'],
    'sk'    => ['name' => 'Slovak',                 'display' => 'Slovenčina',           'direction' => 'ltr'],
    'sl'    => ['name' => 'Slovenian',              'display' => 'Slovenščina',          'direction' => 'ltr'],
    'so'    => ['name' => 'Somali',                 'display' => 'Soomaali',             'direction' => 'ltr'],
    'es'    => ['name' => 'Spanish',                'display' => 'Español',              'direction' => 'ltr'],
    'su'    => ['name' => 'Sundanese',              'display' => 'Basa Sunda',           'direction' => 'ltr'],
    'sw'    => ['name' => 'Swahili',                'display' => 'Kiswahili',            'direction' => 'ltr'],
    'sv'    => ['name' => 'Swedish',                'display' => 'Svenska',              'direction' => 'ltr'],
    'tl'    => ['name' => 'Tagalog (Filipino)',     'display' => 'Filipino',             'direction' => 'ltr'],
    'tg'    => ['name' => 'Tajik',                  'display' => 'Тоҷикӣ',               'direction' => 'ltr'],
    'ta'    => ['name' => 'Tamil',                  'display' => 'தமிழ்',               'direction' => 'ltr'],
    'tt'    => ['name' => 'Tatar',                  'display' => 'Татарча',              'direction' => 'ltr'],
    'te'    => ['name' => 'Telugu',                 'display' => 'తెలుగు',              'direction' => 'ltr'],
    'th'    => ['name' => 'Thai',                   'display' => 'ภาษาไทย',              'direction' => 'ltr'],
    'tr'    => ['name' => 'Turkish',                'display' => 'Türkçe',               'direction' => 'ltr'],
    'tk'    => ['name' => 'Turkmen',                'display' => 'Türkmen',              'direction' => 'ltr'],
    'uk'    => ['name' => 'Ukrainian',              'display' => 'Українська',           'direction' => 'ltr'],
    'ur'    => ['name' => 'Urdu',                   'display' => 'اردو',                'direction' => 'rtl'],
    'ug'    => ['name' => 'Uyghur',                 'display' => 'ئۇيغۇرچە',            'direction' => 'rtl'],
    'uz'    => ['name' => 'Uzbek',                  'display' => 'Oʻzbek',              'direction' => 'ltr'],
    'vi'    => ['name' => 'Vietnamese',             'display' => 'Tiếng Việt',           'direction' => 'ltr'],
    'cy'    => ['name' => 'Welsh',                  'display' => 'Cymraeg',              'direction' => 'ltr'],
    'xh'    => ['name' => 'Xhosa',                  'display' => 'isiXhosa',             'direction' => 'ltr'],
    'yi'    => ['name' => 'Yiddish',                'display' => 'ייִדיש',              'direction' => 'rtl'],
    'yo'    => ['name' => 'Yoruba',                 'display' => 'Yorùbá',               'direction' => 'ltr'],
    'zu'    => ['name' => 'Zulu',                   'display' => 'isiZulu',              'direction' => 'ltr'],
];

/* End of file iso_languages.php */
/* Location: ./application/config/iso_languages.php */
